---
_hotel_id: HOT157
_portal_id: ''
latitude: 42.34878
longitude: -71.09533
name: Hotel Commonwealth
email: ''
phone_number: "--"
address:
  street1: 500 Commonwealth Ave
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02215'
